var mongoose = require('mongoose');

var Schema = mongoose.Schema;
var FinalSchema = new Schema({
	//_id : Schema.ObjectId,
	__v : Number,
	Age: {type: String, default: ''},
	ambitionSelf : {type: String, default: ''},
	banned: Boolean,
	birthday: Date,
	body: {type: String, default: ''},
	colorEyes: {type: String, default: ''},
	Description: {type: String, default: ''},
	doDrugs: {type: String, default: ''},
	drinker: {type: String, default: ''},
	email: {type: String, default: ''},
	firstDate: {type: String, default: ''},
	firstName: {type: String, default: ''},
	HairColor: {type: String, default: ''},
	hashedPassword: {type: String, default: ''},
	hasQuestions: Boolean,
	haveCar: {type: String, default: ''},
	Height: {type: String, default: ''},
	interests: Array,
	kidsHave: {type: String, default: ''},
	kidsWant: {type: String, default: ''},
	lastName: {type: String, default: ''},
	location: Array,
	locationName: {type: String, default: ''},
	longestRel: {type: String, default: ''},
	looking: {type: String, default: ''},
	petsHave: {type: String, default: ''},
	pictures: Array,
	profileHeadline: {type: String, default: ''},
	profilePicture: {type: String, default: ''},
	profileUrl: {type: String, default: ''},
	provider: {type: String, default: ''},
	Religion: {type: String, default: ''},
	relStat: {type: String, default: ''},
	role: {type: String, default: ''},
	salt: {type: String, default: ''},
	saveDate: Date,
	sex: {type: String, default: ''},
	Smoker: {type: String, default: ''},
	type: {type: String, default: ''},
	username: {type: String, default: ''}
});

module.exports = mongoose.model('Final', FinalSchema);